using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Oathlord.Shared.Blacksmith.Anvil;
using Content.Oathlord.Shared.Blacksmith.Anvil.Prototypes;
using Content.Shared.Storage;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Containers;
using Container = Robust.Client.UserInterface.Controls.Container;

namespace Content.Oathlord.Client.Blacksmith.Anvil;

[GenerateTypedNameReferences]
public sealed partial class AnvilWindow : FancyWindow
{
    [Dependency] private IPrototypeManager _proto = default!;
    [Dependency] private IEntityManager _entMan = default!;
    private SharedContainerSystem _container;
    private SpriteSystem _sprite;

    private EntityQuery<AnvilComponent> _anvilQuery;

    private AnvilRecipesWindow? _recipesWindow;

    public Action<ProtoId<AnvilRecipePrototype>>? RecipeSelected;
    public Action<int>? DoHit;

    private EntityUid _owner;

    public AnvilWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _container = _entMan.System<SharedContainerSystem>();
        _sprite = _entMan.System<SpriteSystem>();
        _anvilQuery = _entMan.GetEntityQuery<AnvilComponent>();

        OutputsButton.OnPressed += OutputsButtonOnOnPressed;
    }

    private void OutputsButtonOnOnPressed(BaseButton.ButtonEventArgs obj)
    {
        if (!_container.TryGetContainer(_owner, StorageComponent.ContainerId, out var container) || container.ContainedEntities.Count == 0)
            return;

        _recipesWindow?.Close();
        _recipesWindow = new AnvilRecipesWindow();
        _recipesWindow.SetupWindow(container.ContainedEntities);
        _recipesWindow.RecipeSelected += args => RecipeSelected?.Invoke(args);
        _recipesWindow.OnClose += () => _recipesWindow = null;

        _recipesWindow.OpenCentered();
    }

    public override void Close()
    {
        base.Close();
        _recipesWindow?.Close();
    }

    public void SetOwner(EntityUid owner)
    {
        _owner = owner;
    }

    public void UpdateWindow()
    {
        if (!_anvilQuery.TryComp(_owner, out var anvilComponent) || !_container.TryGetContainer(_owner, StorageComponent.ContainerId, out var container))
            return;

        UpdateViewsContainer(container.ContainedEntities, anvilComponent.AllowedWorkables);
        UpdateRecipe(anvilComponent.SelectedRecipe, anvilComponent.WorkDone);
        UpdateMinigame(anvilComponent.Numbers);
    }

    private void UpdateViewsContainer(IReadOnlyList<EntityUid> entities, int amount)
    {
        ViewsContainer.Children.Clear();
        for (var i = 0; i < amount; i++)
        {
            var metalView = new WorkableMetalView();
            var element = entities.ElementAtOrDefault(i);
            metalView.SetupView(element);

            ViewsContainer.AddChild(metalView);
        }
    }

    private void UpdateRecipe(ProtoId<AnvilRecipePrototype>? recipe, int workDone)
    {
        if (recipe is not { } anvilRecipe|| !_proto.TryIndex(anvilRecipe, out var recipeProto))
        {
            RecipeName.Text = "No recipe has been selected... Click 'Outputs' to select one!";
            RecipeView.Visible = false;
            RecipeView.Texture = null;
            RecipeMinigameContainer.Visible = false;
            WorkNeededBar.Value = WorkNeededBar.MinValue;
            WorkDoneBar.Value = WorkDoneBar.MinValue;
            return;
        }

        if (!_proto.TryIndex(recipeProto.Result, out var entityProto))
            return;

        RecipeName.Text = entityProto.Name;
        RecipeView.Texture = _sprite.Frame0(entityProto);
        RecipeView.Visible = true;

        RecipeMinigameContainer.Visible = true;

        WorkNeededBar.Value = recipeProto.WorkRequired;
        WorkDoneBar.Value = workDone;
    }

    private void UpdateMinigame(List<int> numbers)
    {
        if (!RecipeMinigameContainer.Visible)
            return;

        NegativeNumbersContainer.Children.Clear();
        PositiveNumbersContainer.Children.Clear();
        foreach (var number in numbers)
        {
            if (number < 0)
            {
                SetupHitButton(number, NegativeNumbersContainer);
                continue;
            }

            SetupHitButton(number, PositiveNumbersContainer);
        }
    }

    private void SetupHitButton(int number, Container container)
    {
        var hitButton = new Button();
        hitButton.Text = number > 0 ? $"+{number}" : $"{number}";

        hitButton.OnPressed += _ => HitButtonOnOnPressed(number);

        hitButton.MinSize = new Vector2(32, 32);
        container.AddChild(hitButton);
    }

    private void HitButtonOnOnPressed(int number)
    {
        DoHit?.Invoke(number);
    }
}

