using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Oathlord.Shared.Blacksmith.Anvil;
using Content.Oathlord.Shared.Blacksmith.Anvil.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Oathlord.Client.Blacksmith.Anvil;

[GenerateTypedNameReferences]
public sealed partial class AnvilRecipesWindow : FancyWindow
{
    [Dependency] private IEntityManager _entMan = default!;
    [Dependency] private IPrototypeManager _protoMan = default!;
    private AnvilSystem _anvil;

    public Action<ProtoId<AnvilRecipePrototype>>? RecipeSelected;

    private ProtoId<AnvilRecipePrototype>? _selectedRecipe;

    public AnvilRecipesWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _anvil = _entMan.System<AnvilSystem>();

        SelectRecipeButton.OnPressed += SelectRecipeButtonOnOnPressed;
    }

    private void SelectRecipeButtonOnOnPressed(BaseButton.ButtonEventArgs obj)
    {
        if (_selectedRecipe is not { } recipe)
            return;

        RecipeSelected?.Invoke(recipe);
    }

    public void SetupWindow(IReadOnlyList<EntityUid> metals)
    {
        RecipesContainer.Children.Clear();

        var metalList = metals.ToList();
        var recipes = _anvil.GetRecipes(metalList);
        foreach (var recipe in recipes)
        {
            // we already resolved while getting the recipes
            if (!_protoMan.TryIndex(recipe, out var recipeProto))
                continue;

            var anvilRecipe = new AnvilRecipe();
            anvilRecipe.SetTexture(recipeProto.Result);
            anvilRecipe.RecipeButton.OnPressed += _ =>
            {
                SelectRecipeButton.Disabled = false;
                _selectedRecipe = recipe;
                Log.Info(recipe);
            };

            RecipesContainer.AddChild(anvilRecipe);
        }
    }
}

