using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Oathlord.Client.UserInterface.Systems.ScrollingMovement;

/// <summary>
/// Widget used for representing <see cref="ScrollingMovementComponent.Current"/>, for clarity, to the user
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ScrollingMovementWidget : UIWidget
{
    [Dependency] private IGameTiming _timing = default!;

    private TimeSpan _nextHide;
    private TimeSpan _hideTime = TimeSpan.FromSeconds(1.5f);

    public ScrollingMovementWidget()
    {
        RobustXamlLoader.Load(this);
    }

    /// <summary>
    /// Makes the control visible with correct values, and sets up the timers to hide it after some time
    /// </summary>
    public void Blink(float value)
    {
        _nextHide = _timing.CurTime + _hideTime;

        Visible = true;
        MovementBar.Value = value;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!Visible)
            return;

        // todo: fade out..?
        LayoutContainer.SetPosition(this, UserInterfaceManager.MousePositionScaled.Position - new Vector2(32, 32));
        if (_nextHide > _timing.CurTime)
            return;

        Visible = false;
    }
}

